version: "3.9"
services:
  chatty-db:
    image: postgres:14.2-alpine
    container_name: chatty-db
    hostname: chatty-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - chatty-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - chatty-app

  chatty-ui:
    stdin_open: true
    build:
      context: ./chatty
      dockerfile: ./Dockerfile
    container_name: chatty-ui
    ports:
      - "3000:3000"
    depends_on:
      - chatty-api
    networks:
      - chatty-app

  chatty-api:
    stdin_open: true
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: chatty-api
    ports:
      - "4000:4000"
    restart: always
    networks:
      - chatty-app

networks:
  chatty-app:
    driver: bridge

volumes:
  chatty-data: