version: "3.9"
services:
  chatty-api:
    build:
      context: ./server
      args:
        NODE_ENV: development
    volumes:
      - ./server:/app
      - ignoreAPI:/app/node_modules/
    environment:
      - NODE_ENV=development
    command: npm run dev

  chatty-ui:
    build:
      context: ./chatty
    volumes:
      - ./chatty:/app
      - ignoreUI:/app/node_modules/
volumes:
  ignoreAPI:
  ignoreUI: