version: "3.9"
services:
  chatty-api:
    build:
      context: ./server
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - ignore:/app/node_modules/
    environment:
      - NODE_ENV=development
    command: npm run dev
volumes:
  ignore: